DATASET: "~/Documents/Datasets/VOC/"
ANCHOR_BBOXES: "./checkpoints/anchors/anchor_bboxes_k_5.npy"
IMGSZ: 416
IMG_SIZES: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
SAMPLE_IMGSZ: False
DOWNSAMPLE: 32 # Convolutional layers downsample input image five times (so 2^5=32)
LAMBDA_COORD: 5
LAMBDA_NOOBJ: 0.5
EPOCHS: 165
BATCH_SIZE: 32
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
MAX_LR: 1.e-2
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
WEIGHT_DECAY: 1.e-3
VALID_STEP: False

# For evaluation.
EVAL_CHECKPOINT: "./checkpoints/run-2025-01-22-16-03-23/yolov2-voc.pt"
EVAL_CONF_THRESH: 0.2
EVAL_NMS_THRESH: 0.4
EVAL_SPLIT: "val"
