DATASET: "~/Documents/Datasets/VOC/"
ANCHOR_BBOXES: "./checkpoints/anchor_bboxes_k_5.npy"
IMGSZ: 416
DOWNSAMPLE: 32 # Convolutional layers downsample input image five times (so 2^5=32)
LAMBDA_COORD: 5
LAMBDA_NOOBJ: 0.5
EPOCHS: 135
BATCH_SIZE: 32
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
MAX_LR: 1.e-3
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
WEIGHT_DECAY: 5.e-4
VALID_STEP: False

# For evaluation.
EVAL_CHECKPOINT: "./checkpoints/yolov2-voc-epochs-135.pt"
EVAL_CONF_THRESH: 0.2
EVAL_NMS_THRESH: 0.4
