ARCHITECTURE: GPT-S
CONTEXT_LEN: 256
DROPOUT: 0.0
QKV_BIAS: false
BATCH_SIZE: 4
NUM_WORKERS: 0
PERSISTENT_WORKERS: false
LR: 0.0005
WEIGHT_DECAY: 0.1
NUM_EPOCHS: 20
EVAL_ITER: null

ARCHITECTURES:
  GPT-S:
    EMBEDDING_DIM: 768
    NUM_LAYERS: 12
    NUM_HEADS: 12
  GPT-M:
    EMBEDDING_DIM: 1024
    NUM_LAYERS: 24
    NUM_HEADS: 16
  GPT-L:
    EMBEDDING_DIM: 1280
    NUM_LAYERS: 36
    NUM_HEADS: 20
  GPT-XL:
    EMBEDDING_DIM: 1600
    NUM_LAYERS: 48
    NUM_HEADS: 25
