DATASET: "~/Downloads/VOC2012/train_val"
IMGSZ: 448
S: 7
B: 2
C: 20
LAMBDA_COORD: 5
LAMBDA_NOOBJ: 0.5
EPOCHS: 50
UNFREEZE_BACKBONE: False
EPOCH_TO_UNFREEZE_BACKBONE: 5
BATCH_SIZE: 64
NUM_WORKERS: 8
PERSISTENT_WORKERS: True
PIN_MEMORY: True
MAX_LR: 1.e-2
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
WEIGHT_DECAY: 5.e-4
