DATASET: "~/Documents/Datasets/VOC/"
IMGSZ: 448
S: 7
B: 2
C: 20
LAMBDA_COORD: 5
LAMBDA_NOOBJ: 0.5
EPOCHS: 135
BACKBONE_TRAINABLE: True
BATCH_SIZE: 32
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
MAX_LR: 1.e-3
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
WEIGHT_DECAY: 5.e-4
VALID_STEP: False
EVAL_CHECKPOINT: "./checkpoints/yolov1-voc.pt"
EVAL_CONF_THRESH: 0.05
EVAL_NMS_THRESH: 0.3
