TRAIN_DATASET: "~/Documents/Datasets/COCO/annotations_trainval2017/annotations/person_keypoints_train2017.json"
VALID_DATASET: "~/Documents/Datasets/COCO/annotations_trainval2017/annotations/person_keypoints_val2017.json"
MIN_KEYPOINTS: 12
MAX_KPTS_TO_MASK: 4
RT_ALPHA: 0.6
KL_ALPHA: 0.01
KL_ALPHA_MULTIPLIER: 1.01
LATENT_ALPHA: 0.1
LATENT_ALPHA_MULTIPLIER: 1.01
EPOCHS: 100
BATCH_SIZE: 1024
NUM_WORKERS: 4
PERSISTENT_WORKERS: True
PIN_MEMORY: True
MAX_LR: 1.e-2
DIV_FACTOR: 10
FINAL_DIV_FACTOR: 100
THREE_PHASE: True
ANNEAL_STRATEGY: "cos"
CYCLE_MOMENTUM: True
BASE_MOMENTUM: 0.85
MAX_MOMENTUM: 0.95
WEIGHT_DECAY: 1.e-2
DECOUPLED_WEIGHT_DECAY: True
